name: Deploy Next.js Dashboard to IIS

on:
  push:
    branches: [ "main" ] 

jobs:
  deploy:
    runs-on: self-hosted 
    # Mantenemos el 'defaults' aquí para que npm encuentre el package.json
    defaults:
      run:
        working-directory: ./tarimas-interface

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to IIS folder
        run: |
          # 1. Definimos las rutas. 
          # Como estamos dentro de tarimas-interface, 'out' es la ruta correcta
          $sourcePath = ".\out" 
          $destinationPath = "C:\inetpub\wwwroot\Destiny"

          # 2. Robocopy con el parche para el código 3 (Archivos Extras)
          robocopy $sourcePath $destinationPath /MIR /V /NP /XF web.config

          # 3. Traductor de códigos: Cualquier código menor a 8 es ÉXITO para Robocopy
          if ($lastexitcode -lt 8) { 
              exit 0 
          } else { 
              exit $lastexitcode 
          }
        shell: powershell